export interface PricingPackage { id: string; title: string; category: string; price: string; timeline: string; description: string; features: string[]; image: string; popular?: boolean }

export const pricingPackages: PricingPackage[] = [
  { id: 'colour-care', title: 'Hair Colour & Care', category: 'Hair', price: '₹4,500 onwards', timeline: 'Global colour • Colour care consultation', description: 'Professional colour services with tailored recommendations for your hair.', features: ['Global hair colour', 'Organic colour options', 'Colour maintenance guidance'], image: '/femina/hair-color.webp', popular: true },
  { id: 'bridal', title: 'Bridal Makeup', category: 'Makeup', price: '₹11,000 onwards', timeline: 'Bridal makeup • Hair styling consultation', description: 'A considered bridal look planned around your occasion, outfit and finish.', features: ['Basic bridal makeup', 'HD bridal makeup', 'Salon or destination options'], image: '/femina/bridal.JPG', popular: true },
  { id: 'treatment', title: 'Hair Treatment', category: 'Hair Treatments', price: '₹1,000 onwards', timeline: 'Conditioning • Hair spa • Treatment consultation', description: 'From hydration and scalp care to keratin, Botox and NanoPlastia.', features: ['Deep conditioning', 'Hydration hair spa', 'Keratin and smoothing options'], image: '/femina/hair-color.webp' },
  { id: 'beauty', title: 'Beauty & Skin Care', category: 'Beauty', price: '₹350 onwards', timeline: 'Cleanup • Facial • Waxing consultation', description: 'Everyday beauty care with published base pricing and expert guidance.', features: ['Facials and cleanups', 'Threading and waxing', 'Bleach services'], image: '/femina/beauty.jpg' },
  { id: 'nails', title: 'Nails & Care', category: 'Nails', price: '₹600 onwards', timeline: 'Manicure • Pedicure • Nail consultation', description: 'Relaxed nail-care appointments for a polished, cared-for finish.', features: ['Luxury manicure', 'Luxury pedicure', 'Crystal mani and pedi'], image: '/femina/nails.jpeg' },
  { id: 'hair-systems', title: 'Hair Systems & Wigs', category: 'Hair Systems', price: 'Price on Consultation', timeline: 'Patch • Wig • Maintenance consultation', description: 'Natural-looking hair patch, wig, topper and maintenance services.', features: ['New patch installation', 'Re-tightening and maintenance', 'Custom wigs and toppers'], image: '/femina/hair-patch.webp' },
]
